import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Product, ProductFilters } from "@/lib/types";

const fallbackProducts: Product[] = [
  {
    id: "1",
    title: "Giáo trình Cấu trúc dữ liệu",
    price: 120000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT203",
    description: "Sách còn mới 90%, phù hợp cho IT203.",
    image_urls: ["https://picsum.photos/seed/it-203/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Máy tính Casio FX-580VN X",
    price: 380000,
    category: "Hóa học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "CH102",
    description: "Dùng tốt, pin mới thay.",
    image_urls: ["https://picsum.photos/seed/ch-102/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Bộ dụng cụ thí nghiệm hóa",
    price: 250000,
    category: "Hóa học",
    status: "reserved",
    university_city: "Đà Lạt",
    course_code: "CH210",
    description: "Đặt trước cho lớp Hóa hữu cơ.",
    image_urls: ["https://picsum.photos/seed/ch-210/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Tài liệu Kinh tế vi mô",
    price: 90000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "EC101",
    description: "Bộ đề và slide tổng hợp.",
    image_urls: ["https://picsum.photos/seed/ec-101/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Sách Sinh học tế bào",
    price: 110000,
    category: "Sinh học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "BIO201",
    description: "Sách in màu, có ghi chú.",
    image_urls: ["https://picsum.photos/seed/bio-201/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Laptop Lenovo ThinkPad cũ",
    price: 5200000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT301",
    description: "Core i5, 8GB RAM, SSD 256GB.",
    image_urls: ["https://picsum.photos/seed/it-301/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Máy in mini cho ký túc xá",
    price: 650000,
    category: "Khác",
    status: "available",
    university_city: "Đà Lạt",
    course_code: null,
    description: "In nhanh, tiết kiệm mực.",
    image_urls: ["https://picsum.photos/seed/ktx-print/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Bộ mô hình phân tử hóa học",
    price: 180000,
    category: "Hóa học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "CH105",
    description: "Dùng cho thực hành hóa đại cương.",
    image_urls: ["https://picsum.photos/seed/ch-105/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    title: "Giáo trình Lập trình Web nâng cao",
    price: 150000,
    category: "Công nghệ thông tin",
    status: "reserved",
    university_city: "Đà Lạt",
    course_code: "IT405",
    description: "Có bài tập thực hành kèm đáp án.",
    image_urls: ["https://picsum.photos/seed/it-405/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    title: "Sách Marketing căn bản",
    price: 95000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "MK101",
    description: "Bìa cứng, còn mới.",
    image_urls: ["https://picsum.photos/seed/mk-101/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "11",
    title: "Bộ kit thực hành IoT",
    price: 490000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT450",
    description: "Có cảm biến, board, dây nối đầy đủ.",
    image_urls: ["https://picsum.photos/seed/it-450/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "12",
    title: "Sách Thống kê sinh học",
    price: 130000,
    category: "Sinh học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "BIO310",
    description: "Tổng hợp công thức và ví dụ.",
    image_urls: ["https://picsum.photos/seed/bio-310/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "13",
    title: "Bàn học gấp gọn",
    price: 420000,
    category: "Khác",
    status: "available",
    university_city: "Bảo Lộc",
    course_code: null,
    description: "Nhẹ, dễ di chuyển, phù hợp phòng trọ.",
    image_urls: ["https://picsum.photos/seed/desk-13/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "14",
    title: "Giáo trình Kỹ thuật lập trình",
    price: 140000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT202",
    description: "Có ghi chú và ví dụ thực hành.",
    image_urls: ["https://picsum.photos/seed/it-202/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "15",
    title: "Áo khoác đồng phục khoa",
    price: 160000,
    category: "Khác",
    status: "available",
    university_city: "Đà Lạt",
    course_code: null,
    description: "Size M, còn mới 95%.",
    image_urls: ["https://picsum.photos/seed/jacket-15/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "16",
    title: "Sách Hóa phân tích",
    price: 125000,
    category: "Hóa học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "CH220",
    description: "Có bài tập cuối chương.",
    image_urls: ["https://picsum.photos/seed/ch-220/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "17",
    title: "Kính hiển vi mini",
    price: 290000,
    category: "Sinh học",
    status: "available",
    university_city: "Bảo Lộc",
    course_code: "BIO110",
    description: "Dùng cho thực hành quan sát tế bào.",
    image_urls: ["https://picsum.photos/seed/bio-110/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "18",
    title: "Sách Quản trị học",
    price: 105000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "EC210",
    description: "Tóm tắt chương rõ ràng.",
    image_urls: ["https://picsum.photos/seed/ec-210/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "19",
    title: "Bộ tài liệu SQL cơ bản",
    price: 60000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT150",
    description: "Tài liệu in, có bài tập.",
    image_urls: ["https://picsum.photos/seed/it-150/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "20",
    title: "Sách Kinh tế lượng",
    price: 135000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "EC305",
    description: "Giải thích dễ hiểu, có ví dụ.",
    image_urls: ["https://picsum.photos/seed/ec-305/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "21",
    title: "Kit Arduino cơ bản",
    price: 320000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT230",
    description: "Board + linh kiện cơ bản.",
    image_urls: ["https://picsum.photos/seed/it-230/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "22",
    title: "Sách Sinh học phân tử",
    price: 145000,
    category: "Sinh học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "BIO320",
    description: "Phù hợp học kỳ 5.",
    image_urls: ["https://picsum.photos/seed/bio-320/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "23",
    title: "Sách Tài chính doanh nghiệp",
    price: 125000,
    category: "Kinh tế",
    status: "reserved",
    university_city: "Đà Lạt",
    course_code: "EC330",
    description: "Nhiều bài tập thực hành.",
    image_urls: ["https://picsum.photos/seed/ec-330/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "24",
    title: "Balo laptop chống nước",
    price: 230000,
    category: "Khác",
    status: "available",
    university_city: "Bảo Lộc",
    course_code: null,
    description: "Màu xám, nhiều ngăn.",
    image_urls: ["https://picsum.photos/seed/balo-24/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "25",
    title: "Sách Hệ điều hành",
    price: 155000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT310",
    description: "Có bài lab kèm hướng dẫn.",
    image_urls: ["https://picsum.photos/seed/it-310/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "26",
    title: "Bộ thí nghiệm hóa hữu cơ",
    price: 360000,
    category: "Hóa học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "CH320",
    description: "Dụng cụ đầy đủ, sạch sẽ.",
    image_urls: ["https://picsum.photos/seed/ch-320/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "27",
    title: "Tài liệu Phân tích dữ liệu",
    price: 98000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT340",
    description: "Notebook in, có code ví dụ.",
    image_urls: ["https://picsum.photos/seed/it-340/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "28",
    title: "Sách Hóa vô cơ",
    price: 118000,
    category: "Hóa học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "CH140",
    description: "Phù hợp học kỳ 3.",
    image_urls: ["https://picsum.photos/seed/ch-140/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "29",
    title: "Máy tính bảng phục vụ học tập",
    price: 3200000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Bảo Lộc",
    course_code: "IT210",
    description: "Bút cảm ứng đi kèm.",
    image_urls: ["https://picsum.photos/seed/it-210/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "30",
    title: "Sách Kế toán tài chính",
    price: 110000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "EC220",
    description: "Có ví dụ minh họa.",
    image_urls: ["https://picsum.photos/seed/ec-220/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "31",
    title: "Sách Di truyền học",
    price: 125000,
    category: "Sinh học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "BIO230",
    description: "Tóm tắt chương dễ học.",
    image_urls: ["https://picsum.photos/seed/bio-230/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "32",
    title: "Bộ tài liệu Marketing số",
    price: 115000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "MK205",
    description: "Case study mới nhất.",
    image_urls: ["https://picsum.photos/seed/mk-205/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "33",
    title: "Sách Cơ sở dữ liệu",
    price: 145000,
    category: "Công nghệ thông tin",
    status: "reserved",
    university_city: "Đà Lạt",
    course_code: "IT240",
    description: "Có bài tập và sơ đồ ER.",
    image_urls: ["https://picsum.photos/seed/it-240/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "34",
    title: "Sách Hóa lý",
    price: 128000,
    category: "Hóa học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "CH260",
    description: "Có bảng công thức đầy đủ.",
    image_urls: ["https://picsum.photos/seed/ch-260/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "35",
    title: "Giày thể thao đi học",
    price: 250000,
    category: "Khác",
    status: "available",
    university_city: "Bảo Lộc",
    course_code: null,
    description: "Size 41, mới 90%.",
    image_urls: ["https://picsum.photos/seed/shoes-35/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "36",
    title: "Tài liệu Sinh thái học",
    price: 90000,
    category: "Sinh học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "BIO260",
    description: "Có sơ đồ hệ sinh thái.",
    image_urls: ["https://picsum.photos/seed/bio-260/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "37",
    title: "Giáo trình Mạng máy tính",
    price: 150000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT330",
    description: "Có lab mô phỏng.",
    image_urls: ["https://picsum.photos/seed/it-330/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "38",
    title: "Sách Kinh tế phát triển",
    price: 120000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "EC240",
    description: "Tóm tắt lý thuyết trọng tâm.",
    image_urls: ["https://picsum.photos/seed/ec-240/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "39",
    title: "Bộ test hóa học nhanh",
    price: 210000,
    category: "Hóa học",
    status: "available",
    university_city: "Bảo Lộc",
    course_code: "CH310",
    description: "Dùng kiểm tra định tính.",
    image_urls: ["https://picsum.photos/seed/ch-310/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "40",
    title: "Sách Sinh lý thực vật",
    price: 118000,
    category: "Sinh học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "BIO270",
    description: "In rõ, ít ghi chú.",
    image_urls: ["https://picsum.photos/seed/bio-270/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "41",
    title: "Bộ sách Kỹ năng mềm",
    price: 99000,
    category: "Khác",
    status: "available",
    university_city: "Đà Lạt",
    course_code: null,
    description: "Gồm 3 cuốn kỹ năng.",
    image_urls: ["https://picsum.photos/seed/soft-41/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "42",
    title: "Tai nghe chống ồn",
    price: 450000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Bảo Lộc",
    course_code: "IT115",
    description: "Nghe rõ, pin trâu.",
    image_urls: ["https://picsum.photos/seed/it-115/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "43",
    title: "Sách Quản trị nhân sự",
    price: 112000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "EC250",
    description: "Ví dụ thực tế, dễ hiểu.",
    image_urls: ["https://picsum.photos/seed/ec-250/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "44",
    title: "Bộ kính bảo hộ phòng lab",
    price: 65000,
    category: "Hóa học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "CH001",
    description: "Đạt chuẩn an toàn.",
    image_urls: ["https://picsum.photos/seed/ch-001/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "45",
    title: "Sách Công nghệ sinh học",
    price: 150000,
    category: "Sinh học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "BIO360",
    description: "Phù hợp chuyên ngành.",
    image_urls: ["https://picsum.photos/seed/bio-360/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "46",
    title: "Sách Thống kê ứng dụng",
    price: 115000,
    category: "Kinh tế",
    status: "reserved",
    university_city: "Bảo Lộc",
    course_code: "EC260",
    description: "Có bài tập kèm đáp án.",
    image_urls: ["https://picsum.photos/seed/ec-260/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "47",
    title: "Ổ cứng SSD 256GB",
    price: 520000,
    category: "Công nghệ thông tin",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "IT099",
    description: "Tốc độ cao, bảo hành 6 tháng.",
    image_urls: ["https://picsum.photos/seed/it-099/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "48",
    title: "Sách Hóa đại cương",
    price: 98000,
    category: "Hóa học",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "CH001",
    description: "Dành cho năm nhất.",
    image_urls: ["https://picsum.photos/seed/ch-001b/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "49",
    title: "Sách Giải phẫu học",
    price: 165000,
    category: "Sinh học",
    status: "available",
    university_city: "Bảo Lộc",
    course_code: "BIO180",
    description: "Hình ảnh rõ, dễ học.",
    image_urls: ["https://picsum.photos/seed/bio-180/1200/800"],
    created_at: new Date().toISOString(),
  },
  {
    id: "50",
    title: "Sách Luật kinh tế",
    price: 125000,
    category: "Kinh tế",
    status: "available",
    university_city: "Đà Lạt",
    course_code: "EC290",
    description: "Tóm tắt các chương trọng tâm.",
    image_urls: ["https://picsum.photos/seed/ec-290/1200/800"],
    created_at: new Date().toISOString(),
  }
];

export async function getProducts(filters: ProductFilters): Promise<Product[]> {
  const supabase = createSupabaseServerClient();
  if (!supabase) {
    return filterLocalProducts(fallbackProducts, filters);
  }

  let query = supabase.from("products").select("*").order("created_at", {
    ascending: false,
  });

  if (filters.city) {
    query = query.eq("university_city", filters.city);
  }

  if (filters.course) {
    query = query.ilike("course_code", `%${filters.course}%`);
  }

  if (filters.query) {
    query = query.or(
      `title.ilike.%${filters.query}%,course_code.ilike.%${filters.query}%`
    );
  }

  if (filters.major) {
    query = query.eq("category", filters.major);
  }

  const { data, error } = await query;

  if (error || !data) {
    return filterLocalProducts(fallbackProducts, filters);
  }

  return data as Product[];
}

export async function getProductById(id: string): Promise<Product | null> {
  const supabase = createSupabaseServerClient();
  if (!supabase) {
    return fallbackProducts.find((product) => product.id === id) ?? null;
  }

  const { data, error } = await supabase
    .from("products")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error || !data) {
    return fallbackProducts.find((product) => product.id === id) ?? null;
  }

  return data as Product;
}

function filterLocalProducts(products: Product[], filters: ProductFilters) {
  return products.filter((product) => {
    const matchesCity = filters.city
      ? product.university_city === filters.city
      : true;
    const matchesCourse = filters.course
      ? product.course_code?.toLowerCase().includes(filters.course.toLowerCase())
      : true;
    const matchesQuery = filters.query
      ? product.title.toLowerCase().includes(filters.query.toLowerCase()) ||
        product.course_code?.toLowerCase().includes(filters.query.toLowerCase())
      : true;
    const matchesMajor = filters.major
      ? product.category === filters.major
      : true;
    return matchesCity && matchesCourse && matchesQuery && matchesMajor;
  });
}
